#!/bin/sh

choice=$(printf " Shutdown\n Reboot\n Logout\n Lock\n⏾ Suspend" | dmenu -i -p "Power")

case "$choice" in
    " Shutdown")
        systemctl poweroff
        ;;
    " Reboot")
        systemctl reboot
        ;;
    " Logout")
        pkill dwm
        ;;
    " Lock")
        slock
        ;;
    "⏾ Suspend")
        systemctl suspend
        ;;
esac
