[colors]
; --- WINTER COZY THEME (Nord Based) ---

background = #dd242933
foreground = #D8DEE9
foreground-alt = #4C566A

primary = #88C0D0
secondary = #81A1C1
alert = #BF616A
green = #A3BE8C
yellow = #EBCB8B

blue = #81A1C1
magenta = #B48EAD
white = #ECEFF4
black = #3B4252
