[colors]
; Paleta Gruvbox Material (Dark, Hard)
background = #1d2021
foreground = #d4be98
foreground-alt = #a89984

; Colores de acento
primary = #7daea3
secondary = #d3869b
alert = #ea6962

; Colores completos
black = #32302f
red = #ea6962
green = #a9b665
yellow = #d8a657
blue = #7daea3
magenta = #d3869b
cyan = #89b482
white = #d4be98
