[colors]
; --- GRUVBOX DARK NATURE ---

; Fondo mucho más oscuro (casi negro, pero cálido)
; background = #0f1112
background = #151515
background-alt = #1e1e1e

foreground = #fbf1c7
foreground-alt = #d7c5a7

; EL CAMBIO PRINCIPAL: Tu acento ahora es verde naturaleza
primary = #a3ae6d
secondary = #a9b665

alert = #d67b76
disabled = #867970

; Mantenemos estos por si algún módulo específico los pide
green = #a9b665
yellow = #d8a657
blue = #7daea3
